### ISSUE TITLE
GigaPath input size is 224x224

### ISSUE THREAD

**Issue by jamesdolezal** [georg-wolflein/pathology-feature-extractors#1]
Thanks for putting this list together! One minor correction: the Prov-GigaPath model input size is 224, not 256 (despite what they note in their paper). You can see this in their preprocessing functions [here](https://github.com/prov-gigapath/prov-gigapath/blob/98b8c6674aaad1f3a41ea57b7f59d9b65c9f233c/gigapath/pipeline.py#L106-L115). I've also confirmed this by spinning up their model and attempting to provide it with 256 x 256 images, which results in a shape mismatch error.

**Comment by georg-wolflein** [comment]
Great catch, thank you James!
